site_name: Archive System Blog
site_description: Building a College Document Management System
site_author: arthiccc
copyright: Copyright &copy; 2026 arthiccc

theme:
  name: material
  palette:
    primary: orange
    accent: orange
    scheme: slate
  features:
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Blog: blog/index.md

markdown_extensions:
  - toc:
      permalink: true
  - fenced_code
  - tables
  - admonition

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arthiccc

extra_css:
  - stylesheets/extra.css
